import { ColumnDef } from "@tanstack/react-table";

export type Solicitation = {
  id: string;
  title: string;
  dueDate: string;
  solicitationSummary: string;
  mainCategory: string;
  solicitationType: string;
  attachments: string[];
};

export const solicitationsColumns: ColumnDef<Solicitation>[] = [
  {
    accessorKey: "id",
    header: "Id",
  },
  {
    accessorKey: "title",
    header: "Title",
  },
  {
    accessorKey: "dueDate",
    header: "Due Date",
  },
  {
    accessorKey: "solicitationSummary",
    header: "Solicitation Summary",
  },
  {
    accessorKey: "mainCategory",
    header: "Main Category",
  },
  {
    accessorKey: "solicitationType",
    header: "Solicitation Type",
  },
  {
    accessorKey: "attachments",
    header: "Attachments",
  },
];

export const solicitations: Solicitation[] = [
  {
    title: "Marketing Services 1",
    id: "10000",
    dueDate: "2024-08-14",
    solicitationSummary: "Summary for marketing services 1",
    mainCategory: "Consulting",
    solicitationType: "RFQ",
    attachments: ["document1.pdf", "attachment1.docx"],
  },
  {
    title: "Software Development 2",
    id: "10001",
    dueDate: "2024-01-28",
    solicitationSummary: "Summary for software development 2",
    mainCategory: "IT",
    solicitationType: "RFP",
    attachments: ["document2.pdf", "attachment2.docx"],
  },
  {
    title: "IT Support 3",
    id: "10002",
    dueDate: "2024-10-25",
    solicitationSummary: "Summary for it support 3",
    mainCategory: "IT",
    solicitationType: "RFI",
    attachments: ["document3.pdf", "attachment3.docx"],
  },
  {
    title: "IT Support 4",
    id: "10003",
    dueDate: "2024-10-26",
    solicitationSummary: "Summary for it support 4",
    mainCategory: "Management",
    solicitationType: "RFI",
    attachments: ["document4.pdf", "attachment4.docx"],
  },
  {
    title: "Software Development 5",
    id: "10004",
    dueDate: "2024-02-17",
    solicitationSummary: "Summary for software development 5",
    mainCategory: "Management",
    solicitationType: "RFQ",
    attachments: ["document5.pdf", "attachment5.docx"],
  },
  {
    title: "Consulting Services 6",
    id: "10005",
    dueDate: "2024-09-27",
    solicitationSummary: "Summary for consulting services 6",
    mainCategory: "Management",
    solicitationType: "RFQ",
    attachments: ["document6.pdf", "attachment6.docx"],
  },
  {
    title: "Facility Management 7",
    id: "10006",
    dueDate: "2024-08-28",
    solicitationSummary: "Summary for facility management 7",
    mainCategory: "Construction",
    solicitationType: "RFQ",
    attachments: ["document7.pdf", "attachment7.docx"],
  },
  {
    title: "Marketing Services 8",
    id: "10007",
    dueDate: "2024-05-11",
    solicitationSummary: "Summary for marketing services 8",
    mainCategory: "Management",
    solicitationType: "RFQ",
    attachments: ["document8.pdf", "attachment8.docx"],
  },
  {
    title: "Consulting Services 9",
    id: "10008",
    dueDate: "2024-03-12",
    solicitationSummary: "Summary for consulting services 9",
    mainCategory: "Management",
    solicitationType: "RFQ",
    attachments: ["document9.pdf", "attachment9.docx"],
  },
  {
    title: "Software Development 10",
    id: "10009",
    dueDate: "2024-09-05",
    solicitationSummary: "Summary for software development 10",
    mainCategory: "Consulting",
    solicitationType: "RFQ",
    attachments: ["document10.pdf", "attachment10.docx"],
  },
  {
    title: "Construction Project 11",
    id: "10010",
    dueDate: "2024-12-10",
    solicitationSummary: "Summary for construction project 11",
    mainCategory: "IT",
    solicitationType: "RFQ",
    attachments: ["document11.pdf", "attachment11.docx"],
  },
  {
    title: "IT Support 12",
    id: "10011",
    dueDate: "2024-09-15",
    solicitationSummary: "Summary for it support 12",
    mainCategory: "IT",
    solicitationType: "RFI",
    attachments: ["document12.pdf", "attachment12.docx"],
  },
  {
    title: "Software Development 13",
    id: "10012",
    dueDate: "2024-07-26",
    solicitationSummary: "Summary for software development 13",
    mainCategory: "Marketing",
    solicitationType: "RFP",
    attachments: ["document13.pdf", "attachment13.docx"],
  },
  {
    title: "IT Support 14",
    id: "10013",
    dueDate: "2024-02-10",
    solicitationSummary: "Summary for it support 14",
    mainCategory: "IT",
    solicitationType: "RFP",
    attachments: ["document14.pdf", "attachment14.docx"],
  },
  {
    title: "Facility Management 15",
    id: "10014",
    dueDate: "2024-06-09",
    solicitationSummary: "Summary for facility management 15",
    mainCategory: "IT",
    solicitationType: "RFQ",
    attachments: ["document15.pdf", "attachment15.docx"],
  },
  {
    title: "Facility Management 16",
    id: "10015",
    dueDate: "2024-06-14",
    solicitationSummary: "Summary for facility management 16",
    mainCategory: "Marketing",
    solicitationType: "RFP",
    attachments: ["document16.pdf", "attachment16.docx"],
  },
  {
    title: "Software Development 17",
    id: "10016",
    dueDate: "2024-01-14",
    solicitationSummary: "Summary for software development 17",
    mainCategory: "Consulting",
    solicitationType: "RFQ",
    attachments: ["document17.pdf", "attachment17.docx"],
  },
  {
    title: "Construction Project 18",
    id: "10017",
    dueDate: "2024-07-25",
    solicitationSummary: "Summary for construction project 18",
    mainCategory: "Support",
    solicitationType: "RFQ",
    attachments: ["document18.pdf", "attachment18.docx"],
  },
  {
    title: "Consulting Services 19",
    id: "10018",
    dueDate: "2024-05-23",
    solicitationSummary: "Summary for consulting services 19",
    mainCategory: "IT",
    solicitationType: "RFQ",
    attachments: ["document19.pdf", "attachment19.docx"],
  },
  {
    title: "Facility Management 20",
    id: "10019",
    dueDate: "2024-03-20",
    solicitationSummary: "Summary for facility management 20",
    mainCategory: "Support",
    solicitationType: "RFP",
    attachments: ["document20.pdf", "attachment20.docx"],
  },
  {
    title: "IT Support 21",
    id: "10020",
    dueDate: "2024-11-25",
    solicitationSummary: "Summary for it support 21",
    mainCategory: "Construction",
    solicitationType: "RFQ",
    attachments: ["document21.pdf", "attachment21.docx"],
  },
  {
    title: "Construction Project 22",
    id: "10021",
    dueDate: "2024-06-03",
    solicitationSummary: "Summary for construction project 22",
    mainCategory: "Consulting",
    solicitationType: "RFQ",
    attachments: ["document22.pdf", "attachment22.docx"],
  },
  {
    title: "Consulting Services 23",
    id: "10022",
    dueDate: "2024-05-18",
    solicitationSummary: "Summary for consulting services 23",
    mainCategory: "Construction",
    solicitationType: "RFQ",
    attachments: ["document23.pdf", "attachment23.docx"],
  },
  {
    title: "Consulting Services 24",
    id: "10023",
    dueDate: "2024-08-07",
    solicitationSummary: "Summary for consulting services 24",
    mainCategory: "Construction",
    solicitationType: "RFQ",
    attachments: ["document24.pdf", "attachment24.docx"],
  },
  {
    title: "Consulting Services 25",
    id: "10024",
    dueDate: "2024-02-11",
    solicitationSummary: "Summary for consulting services 25",
    mainCategory: "Construction",
    solicitationType: "RFQ",
    attachments: ["document25.pdf", "attachment25.docx"],
  },
  {
    title: "Software Development 26",
    id: "10025",
    dueDate: "2024-04-03",
    solicitationSummary: "Summary for software development 26",
    mainCategory: "Marketing",
    solicitationType: "RFQ",
    attachments: ["document26.pdf", "attachment26.docx"],
  },
  {
    title: "Marketing Services 27",
    id: "10026",
    dueDate: "2024-11-11",
    solicitationSummary: "Summary for marketing services 27",
    mainCategory: "Construction",
    solicitationType: "RFI",
    attachments: ["document27.pdf", "attachment27.docx"],
  },
  {
    title: "Facility Management 28",
    id: "10027",
    dueDate: "2024-09-28",
    solicitationSummary: "Summary for facility management 28",
    mainCategory: "Consulting",
    solicitationType: "RFQ",
    attachments: ["document28.pdf", "attachment28.docx"],
  },
  {
    title: "IT Support 29",
    id: "10028",
    dueDate: "2024-04-16",
    solicitationSummary: "Summary for it support 29",
    mainCategory: "Management",
    solicitationType: "RFP",
    attachments: ["document29.pdf", "attachment29.docx"],
  },
  {
    title: "Software Development 30",
    id: "10029",
    dueDate: "2024-03-26",
    solicitationSummary: "Summary for software development 30",
    mainCategory: "Consulting",
    solicitationType: "RFQ",
    attachments: ["document30.pdf", "attachment30.docx"],
  },
  {
    title: "IT Support 31",
    id: "10030",
    dueDate: "2024-03-02",
    solicitationSummary: "Summary for it support 31",
    mainCategory: "Management",
    solicitationType: "RFP",
    attachments: ["document31.pdf", "attachment31.docx"],
  },
  {
    title: "Facility Management 32",
    id: "10031",
    dueDate: "2024-04-09",
    solicitationSummary: "Summary for facility management 32",
    mainCategory: "IT",
    solicitationType: "RFQ",
    attachments: ["document32.pdf", "attachment32.docx"],
  },
  {
    title: "Consulting Services 33",
    id: "10032",
    dueDate: "2024-08-21",
    solicitationSummary: "Summary for consulting services 33",
    mainCategory: "Consulting",
    solicitationType: "RFQ",
    attachments: ["document33.pdf", "attachment33.docx"],
  },
  {
    title: "Facility Management 34",
    id: "10033",
    dueDate: "2024-03-11",
    solicitationSummary: "Summary for facility management 34",
    mainCategory: "IT",
    solicitationType: "RFQ",
    attachments: ["document34.pdf", "attachment34.docx"],
  },
  {
    title: "Construction Project 35",
    id: "10034",
    dueDate: "2024-10-28",
    solicitationSummary: "Summary for construction project 35",
    mainCategory: "Management",
    solicitationType: "RFQ",
    attachments: ["document35.pdf", "attachment35.docx"],
  },
  {
    title: "Facility Management 36",
    id: "10035",
    dueDate: "2024-12-18",
    solicitationSummary: "Summary for facility management 36",
    mainCategory: "IT",
    solicitationType: "RFQ",
    attachments: ["document36.pdf", "attachment36.docx"],
  },
  {
    title: "Software Development 37",
    id: "10036",
    dueDate: "2024-04-13",
    solicitationSummary: "Summary for software development 37",
    mainCategory: "Consulting",
    solicitationType: "RFI",
    attachments: ["document37.pdf", "attachment37.docx"],
  },
  {
    title: "Software Development 38",
    id: "10037",
    dueDate: "2024-06-03",
    solicitationSummary: "Summary for software development 38",
    mainCategory: "Management",
    solicitationType: "RFP",
    attachments: ["document38.pdf", "attachment38.docx"],
  },
  {
    title: "Construction Project 39",
    id: "10038",
    dueDate: "2024-01-13",
    solicitationSummary: "Summary for construction project 39",
    mainCategory: "Support",
    solicitationType: "RFI",
    attachments: ["document39.pdf", "attachment39.docx"],
  },
  {
    title: "Software Development 40",
    id: "10039",
    dueDate: "2024-02-10",
    solicitationSummary: "Summary for software development 40",
    mainCategory: "Support",
    solicitationType: "RFQ",
    attachments: ["document40.pdf", "attachment40.docx"],
  },
  {
    title: "IT Support 41",
    id: "10040",
    dueDate: "2024-03-01",
    solicitationSummary: "Summary for it support 41",
    mainCategory: "Consulting",
    solicitationType: "RFP",
    attachments: ["document41.pdf", "attachment41.docx"],
  },
  {
    title: "Construction Project 42",
    id: "10041",
    dueDate: "2024-03-15",
    solicitationSummary: "Summary for construction project 42",
    mainCategory: "IT",
    solicitationType: "RFQ",
    attachments: ["document42.pdf", "attachment42.docx"],
  },
  {
    title: "Software Development 43",
    id: "10042",
    dueDate: "2024-01-20",
    solicitationSummary: "Summary for software development 43",
    mainCategory: "Support",
    solicitationType: "RFI",
    attachments: ["document43.pdf", "attachment43.docx"],
  },
  {
    title: "Consulting Services 44",
    id: "10043",
    dueDate: "2024-04-02",
    solicitationSummary: "Summary for consulting services 44",
    mainCategory: "Construction",
    solicitationType: "RFQ",
    attachments: ["document44.pdf", "attachment44.docx"],
  },
  {
    title: "Marketing Services 45",
    id: "10044",
    dueDate: "2024-05-27",
    solicitationSummary: "Summary for marketing services 45",
    mainCategory: "Consulting",
    solicitationType: "RFI",
    attachments: ["document45.pdf", "attachment45.docx"],
  },
  {
    title: "IT Support 46",
    id: "10045",
    dueDate: "2024-08-12",
    solicitationSummary: "Summary for it support 46",
    mainCategory: "Marketing",
    solicitationType: "RFQ",
    attachments: ["document46.pdf", "attachment46.docx"],
  },
  {
    title: "Facility Management 47",
    id: "10046",
    dueDate: "2024-05-23",
    solicitationSummary: "Summary for facility management 47",
    mainCategory: "Consulting",
    solicitationType: "RFQ",
    attachments: ["document47.pdf", "attachment47.docx"],
  },
  {
    title: "IT Support 48",
    id: "10047",
    dueDate: "2024-02-11",
    solicitationSummary: "Summary for it support 48",
    mainCategory: "Marketing",
    solicitationType: "RFQ",
    attachments: ["document48.pdf", "attachment48.docx"],
  },
  {
    title: "Facility Management 49",
    id: "10048",
    dueDate: "2024-05-07",
    solicitationSummary: "Summary for facility management 49",
    mainCategory: "Consulting",
    solicitationType: "RFQ",
    attachments: ["document49.pdf", "attachment49.docx"],
  },
  {
    title: "Software Development 50",
    id: "10049",
    dueDate: "2024-01-21",
    solicitationSummary: "Summary for software development 50",
    mainCategory: "Marketing",
    solicitationType: "RFQ",
    attachments: ["document50.pdf", "attachment50.docx"],
  },
  {
    title: "IT Support 51",
    id: "10050",
    dueDate: "2024-01-16",
    solicitationSummary: "Summary for it support 51",
    mainCategory: "Management",
    solicitationType: "RFQ",
    attachments: ["document51.pdf", "attachment51.docx"],
  },
  {
    title: "Facility Management 52",
    id: "10051",
    dueDate: "2024-11-15",
    solicitationSummary: "Summary for facility management 52",
    mainCategory: "IT",
    solicitationType: "RFI",
    attachments: ["document52.pdf", "attachment52.docx"],
  },
  {
    title: "Software Development 53",
    id: "10052",
    dueDate: "2024-10-21",
    solicitationSummary: "Summary for software development 53",
    mainCategory: "IT",
    solicitationType: "RFI",
    attachments: ["document53.pdf", "attachment53.docx"],
  },
  {
    title: "Software Development 54",
    id: "10053",
    dueDate: "2024-11-19",
    solicitationSummary: "Summary for software development 54",
    mainCategory: "IT",
    solicitationType: "RFI",
    attachments: ["document54.pdf", "attachment54.docx"],
  },
  {
    title: "Consulting Services 55",
    id: "10054",
    dueDate: "2024-12-25",
    solicitationSummary: "Summary for consulting services 55",
    mainCategory: "Marketing",
    solicitationType: "RFQ",
    attachments: ["document55.pdf", "attachment55.docx"],
  },
  {
    title: "Consulting Services 56",
    id: "10055",
    dueDate: "2024-08-15",
    solicitationSummary: "Summary for consulting services 56",
    mainCategory: "Management",
    solicitationType: "RFP",
    attachments: ["document56.pdf", "attachment56.docx"],
  },
  {
    title: "IT Support 57",
    id: "10056",
    dueDate: "2024-08-15",
    solicitationSummary: "Summary for it support 57",
    mainCategory: "Consulting",
    solicitationType: "RFP",
    attachments: ["document57.pdf", "attachment57.docx"],
  },
  {
    title: "Facility Management 58",
    id: "10057",
    dueDate: "2024-11-15",
    solicitationSummary: "Summary for facility management 58",
    mainCategory: "Marketing",
    solicitationType: "RFQ",
    attachments: ["document58.pdf", "attachment58.docx"],
  },
  {
    title: "Facility Management 59",
    id: "10058",
    dueDate: "2024-09-18",
    solicitationSummary: "Summary for facility management 59",
    mainCategory: "Marketing",
    solicitationType: "RFQ",
    attachments: ["document59.pdf", "attachment59.docx"],
  },
  {
    title: "Software Development 60",
    id: "10059",
    dueDate: "2024-02-28",
    solicitationSummary: "Summary for software development 60",
    mainCategory: "Marketing",
    solicitationType: "RFI",
    attachments: ["document60.pdf", "attachment60.docx"],
  },
  {
    title: "Marketing Services 61",
    id: "10060",
    dueDate: "2024-04-13",
    solicitationSummary: "Summary for marketing services 61",
    mainCategory: "Support",
    solicitationType: "RFI",
    attachments: ["document61.pdf", "attachment61.docx"],
  },
  {
    title: "IT Support 62",
    id: "10061",
    dueDate: "2024-03-19",
    solicitationSummary: "Summary for it support 62",
    mainCategory: "Management",
    solicitationType: "RFQ",
    attachments: ["document62.pdf", "attachment62.docx"],
  },
  {
    title: "IT Support 63",
    id: "10062",
    dueDate: "2024-02-27",
    solicitationSummary: "Summary for it support 63",
    mainCategory: "IT",
    solicitationType: "RFP",
    attachments: ["document63.pdf", "attachment63.docx"],
  },
  {
    title: "Marketing Services 64",
    id: "10063",
    dueDate: "2024-09-06",
    solicitationSummary: "Summary for marketing services 64",
    mainCategory: "Marketing",
    solicitationType: "RFP",
    attachments: ["document64.pdf", "attachment64.docx"],
  },
  {
    title: "Consulting Services 65",
    id: "10064",
    dueDate: "2024-05-18",
    solicitationSummary: "Summary for consulting services 65",
    mainCategory: "Marketing",
    solicitationType: "RFQ",
    attachments: ["document65.pdf", "attachment65.docx"],
  },
  {
    title: "Software Development 66",
    id: "10065",
    dueDate: "2024-12-22",
    solicitationSummary: "Summary for software development 66",
    mainCategory: "Construction",
    solicitationType: "RFI",
    attachments: ["document66.pdf", "attachment66.docx"],
  },
  {
    title: "IT Support 67",
    id: "10066",
    dueDate: "2024-03-09",
    solicitationSummary: "Summary for it support 67",
    mainCategory: "Marketing",
    solicitationType: "RFI",
    attachments: ["document67.pdf", "attachment67.docx"],
  },
  {
    title: "Construction Project 68",
    id: "10067",
    dueDate: "2024-07-27",
    solicitationSummary: "Summary for construction project 68",
    mainCategory: "IT",
    solicitationType: "RFP",
    attachments: ["document68.pdf", "attachment68.docx"],
  },
  {
    title: "Marketing Services 69",
    id: "10068",
    dueDate: "2024-01-22",
    solicitationSummary: "Summary for marketing services 69",
    mainCategory: "Consulting",
    solicitationType: "RFI",
    attachments: ["document69.pdf", "attachment69.docx"],
  },
  {
    title: "Facility Management 70",
    id: "10069",
    dueDate: "2024-02-14",
    solicitationSummary: "Summary for facility management 70",
    mainCategory: "Management",
    solicitationType: "RFP",
    attachments: ["document70.pdf", "attachment70.docx"],
  },
  {
    title: "Marketing Services 71",
    id: "10070",
    dueDate: "2024-12-15",
    solicitationSummary: "Summary for marketing services 71",
    mainCategory: "Marketing",
    solicitationType: "RFQ",
    attachments: ["document71.pdf", "attachment71.docx"],
  },
  {
    title: "Software Development 72",
    id: "10071",
    dueDate: "2024-10-03",
    solicitationSummary: "Summary for software development 72",
    mainCategory: "Support",
    solicitationType: "RFI",
    attachments: ["document72.pdf", "attachment72.docx"],
  },
  {
    title: "Consulting Services 73",
    id: "10072",
    dueDate: "2024-01-17",
    solicitationSummary: "Summary for consulting services 73",
    mainCategory: "Support",
    solicitationType: "RFI",
    attachments: ["document73.pdf", "attachment73.docx"],
  },
  {
    title: "IT Support 74",
    id: "10073",
    dueDate: "2024-08-10",
    solicitationSummary: "Summary for it support 74",
    mainCategory: "Marketing",
    solicitationType: "RFQ",
    attachments: ["document74.pdf", "attachment74.docx"],
  },
  {
    title: "Construction Project 75",
    id: "10074",
    dueDate: "2024-04-27",
    solicitationSummary: "Summary for construction project 75",
    mainCategory: "Construction",
    solicitationType: "RFQ",
    attachments: ["document75.pdf", "attachment75.docx"],
  },
  {
    title: "IT Support 76",
    id: "10075",
    dueDate: "2024-07-14",
    solicitationSummary: "Summary for it support 76",
    mainCategory: "Management",
    solicitationType: "RFQ",
    attachments: ["document76.pdf", "attachment76.docx"],
  },
  {
    title: "Consulting Services 77",
    id: "10076",
    dueDate: "2024-11-12",
    solicitationSummary: "Summary for consulting services 77",
    mainCategory: "Support",
    solicitationType: "RFQ",
    attachments: ["document77.pdf", "attachment77.docx"],
  },
  {
    title: "Construction Project 78",
    id: "10077",
    dueDate: "2024-04-27",
    solicitationSummary: "Summary for construction project 78",
    mainCategory: "Consulting",
    solicitationType: "RFP",
    attachments: ["document78.pdf", "attachment78.docx"],
  },
  {
    title: "Construction Project 79",
    id: "10078",
    dueDate: "2024-04-18",
    solicitationSummary: "Summary for construction project 79",
    mainCategory: "IT",
    solicitationType: "RFQ",
    attachments: ["document79.pdf", "attachment79.docx"],
  },
  {
    title: "Construction Project 80",
    id: "10079",
    dueDate: "2024-07-08",
    solicitationSummary: "Summary for construction project 80",
    mainCategory: "IT",
    solicitationType: "RFI",
    attachments: ["document80.pdf", "attachment80.docx"],
  },
  {
    title: "Construction Project 81",
    id: "10080",
    dueDate: "2024-01-03",
    solicitationSummary: "Summary for construction project 81",
    mainCategory: "Construction",
    solicitationType: "RFP",
    attachments: ["document81.pdf", "attachment81.docx"],
  },
  {
    title: "Software Development 82",
    id: "10081",
    dueDate: "2024-10-13",
    solicitationSummary: "Summary for software development 82",
    mainCategory: "Support",
    solicitationType: "RFI",
    attachments: ["document82.pdf", "attachment82.docx"],
  },
  {
    title: "Marketing Services 83",
    id: "10082",
    dueDate: "2024-07-23",
    solicitationSummary: "Summary for marketing services 83",
    mainCategory: "Support",
    solicitationType: "RFI",
    attachments: ["document83.pdf", "attachment83.docx"],
  },
  {
    title: "Marketing Services 84",
    id: "10083",
    dueDate: "2024-09-10",
    solicitationSummary: "Summary for marketing services 84",
    mainCategory: "Construction",
    solicitationType: "RFP",
    attachments: ["document84.pdf", "attachment84.docx"],
  },
  {
    title: "IT Support 85",
    id: "10084",
    dueDate: "2024-01-09",
    solicitationSummary: "Summary for it support 85",
    mainCategory: "Marketing",
    solicitationType: "RFI",
    attachments: ["document85.pdf", "attachment85.docx"],
  },
  {
    title: "Facility Management 86",
    id: "10085",
    dueDate: "2024-11-23",
    solicitationSummary: "Summary for facility management 86",
    mainCategory: "Construction",
    solicitationType: "RFP",
    attachments: ["document86.pdf", "attachment86.docx"],
  },
  {
    title: "Facility Management 87",
    id: "10086",
    dueDate: "2024-12-09",
    solicitationSummary: "Summary for facility management 87",
    mainCategory: "Marketing",
    solicitationType: "RFQ",
    attachments: ["document87.pdf", "attachment87.docx"],
  },
  {
    title: "Consulting Services 88",
    id: "10087",
    dueDate: "2024-12-20",
    solicitationSummary: "Summary for consulting services 88",
    mainCategory: "Construction",
    solicitationType: "RFI",
    attachments: ["document88.pdf", "attachment88.docx"],
  },
  {
    title: "Marketing Services 89",
    id: "10088",
    dueDate: "2024-08-17",
    solicitationSummary: "Summary for marketing services 89",
    mainCategory: "Consulting",
    solicitationType: "RFQ",
    attachments: ["document89.pdf", "attachment89.docx"],
  },
  {
    title: "IT Support 90",
    id: "10089",
    dueDate: "2024-12-11",
    solicitationSummary: "Summary for it support 90",
    mainCategory: "Marketing",
    solicitationType: "RFI",
    attachments: ["document90.pdf", "attachment90.docx"],
  },
  {
    title: "Construction Project 91",
    id: "10090",
    dueDate: "2024-08-15",
    solicitationSummary: "Summary for construction project 91",
    mainCategory: "Support",
    solicitationType: "RFP",
    attachments: ["document91.pdf", "attachment91.docx"],
  },
  {
    title: "IT Support 92",
    id: "10091",
    dueDate: "2024-09-12",
    solicitationSummary: "Summary for it support 92",
    mainCategory: "Management",
    solicitationType: "RFI",
    attachments: ["document92.pdf", "attachment92.docx"],
  },
  {
    title: "Facility Management 93",
    id: "10092",
    dueDate: "2024-12-17",
    solicitationSummary: "Summary for facility management 93",
    mainCategory: "Management",
    solicitationType: "RFI",
    attachments: ["document93.pdf", "attachment93.docx"],
  },
  {
    title: "Consulting Services 94",
    id: "10093",
    dueDate: "2024-02-09",
    solicitationSummary: "Summary for consulting services 94",
    mainCategory: "Support",
    solicitationType: "RFP",
    attachments: ["document94.pdf", "attachment94.docx"],
  },
  {
    title: "Consulting Services 95",
    id: "10094",
    dueDate: "2024-08-19",
    solicitationSummary: "Summary for consulting services 95",
    mainCategory: "Consulting",
    solicitationType: "RFQ",
    attachments: ["document95.pdf", "attachment95.docx"],
  },
  {
    title: "Facility Management 96",
    id: "10095",
    dueDate: "2024-07-23",
    solicitationSummary: "Summary for facility management 96",
    mainCategory: "IT",
    solicitationType: "RFP",
    attachments: ["document96.pdf", "attachment96.docx"],
  },
  {
    title: "Construction Project 97",
    id: "10096",
    dueDate: "2024-05-09",
    solicitationSummary: "Summary for construction project 97",
    mainCategory: "Marketing",
    solicitationType: "RFP",
    attachments: ["document97.pdf", "attachment97.docx"],
  },
  {
    title: "Facility Management 98",
    id: "10097",
    dueDate: "2024-04-20",
    solicitationSummary: "Summary for facility management 98",
    mainCategory: "Management",
    solicitationType: "RFQ",
    attachments: ["document98.pdf", "attachment98.docx"],
  },
  {
    title: "Construction Project 99",
    id: "10098",
    dueDate: "2024-06-01",
    solicitationSummary: "Summary for construction project 99",
    mainCategory: "Consulting",
    solicitationType: "RFP",
    attachments: ["document99.pdf", "attachment99.docx"],
  },
  {
    title: "Facility Management 100",
    id: "10099",
    dueDate: "2024-03-22",
    solicitationSummary: "Summary for facility management 100",
    mainCategory: "IT",
    solicitationType: "RFQ",
    attachments: ["document100.pdf", "attachment100.docx"],
  },
];
